import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './lib/**/*.{ts,tsx}',
  ],
  theme: {
    // ── Full overrides (no default gray/blue palettes) ──
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      white: '#ffffff',
      black: '#000000',
      brand: {
        DEFAULT: 'var(--brand)',
        700:     'var(--brand-700)',
        500:     'var(--brand-500)',
        300:     'var(--brand-300)',
        100:     'var(--brand-100)',
        '050':   'var(--brand-050)',
      },
      ink: {
        900:       'var(--ink-900)',
        700:       'var(--ink-700)',
        500:       'var(--ink-500)',
        300:       'var(--ink-300)',
        'on-brand':'var(--ink-on-brand)',
      },
      bg:      'var(--bg)',
      surface: { DEFAULT: 'var(--surface)', 2: 'var(--surface-2)' },
      line:    { DEFAULT: 'var(--line)', 2: 'var(--line-2)' },
      divider: 'var(--divider)',
      success: 'var(--success)',
      warn:    'var(--warn)',
      danger:  { DEFAULT: 'var(--danger)', soft: 'var(--danger-soft)' },
      c1: { DEFAULT: 'var(--c1)', soft: 'var(--c1-soft)' },
      c2: { DEFAULT: 'var(--c2)', soft: 'var(--c2-soft)' },
      c3: { DEFAULT: 'var(--c3)', soft: 'var(--c3-soft)' },
      c4: { DEFAULT: 'var(--c4)', soft: 'var(--c4-soft)' },
      c5: { DEFAULT: 'var(--c5)', soft: 'var(--c5-soft)' },
      c6: { DEFAULT: 'var(--c6)', soft: 'var(--c6-soft)' },
      c7: { DEFAULT: 'var(--c7)', soft: 'var(--c7-soft)' },
      c8: { DEFAULT: 'var(--c8)', soft: 'var(--c8-soft)' },
      c9: { DEFAULT: 'var(--c9)', soft: 'var(--c9-soft)' },
      c10:{ DEFAULT: 'var(--c10)', soft: 'var(--c10-soft)' },
    },
    fontFamily: {
      kr: ['var(--font-kr)', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Apple SD Gothic Neo', 'Noto Sans KR', 'sans-serif'],
      en: ['var(--font-en)', 'ui-monospace', 'SF Mono', 'Menlo', 'Consolas', 'monospace'],
    },
    fontSize: {
      caption:  ['12px', { lineHeight: '16px' }],
      callout:  ['14px', { lineHeight: '20px' }],
      body:     ['16px', { lineHeight: '24px' }],
      subtitle: ['20px', { lineHeight: '28px' }],
      title:    ['24px', { lineHeight: '32px' }],
      headline: ['28px', { lineHeight: '36px' }],
      display:  ['32px', { lineHeight: '40px' }],
    },
    letterSpacing: {
      tighter: '-0.02em',
      tight:   '-0.01em',
      normal:   '0em',
      wide:     '0.04em',
      wider:    '0.06em',
    },
    borderRadius: {
      none: '0',
      xs:   '6px',
      sm:   '8px',
      md:   '12px',
      lg:   '16px',
      xl:   '22px',
      pill: '999px',
      full: '9999px',
    },
    extend: {
      keyframes: {
        'slide-up': {
          from: { transform: 'translateY(100%)' },
          to:   { transform: 'translateY(0)' },
        },
        'fade-in': {
          from: { opacity: '0', transform: 'translateY(-4px)' },
          to:   { opacity: '1', transform: 'translateY(0)' },
        },
        // Bottom-sheet animations bake the centering translate(-50%) into
        // the keyframe so it isn't lost while the animation is running.
        'sheet-up': {
          from: { transform: 'translate(-50%, 100%)' },
          to:   { transform: 'translate(-50%, 0)' },
        },
        'sheet-down': {
          from: { transform: 'translate(-50%, 0)' },
          to:   { transform: 'translate(-50%, 100%)' },
        },
        'backdrop-in':  { from: { opacity: '0' }, to: { opacity: '1' } },
        'backdrop-out': { from: { opacity: '1' }, to: { opacity: '0' } },
      },
      animation: {
        'slide-up': 'slide-up .28s cubic-bezier(.2,.8,.2,1)',
        'fade-in':  'fade-in .22s ease',
        // Material 3 emphasized easings.
        'sheet-up':     'sheet-up .35s cubic-bezier(.05,.7,.1,1) both',
        'sheet-down':   'sheet-down .2s cubic-bezier(.3,0,.8,.15) both',
        'backdrop-in':  'backdrop-in .25s ease-out both',
        'backdrop-out': 'backdrop-out .18s ease-in both',
      },
      fontWeight: {
        regular:   '400',
        medium:    '500',
        semibold:  '600',
        bold:      '700',
        extrabold: '800',
      },
      boxShadow: {
        sh1:       '0 1px 2px rgba(13,30,55,.05)',
        sh2:       '0 2px 6px rgba(13,30,55,.06), 0 1px 2px rgba(13,30,55,.04)',
        sh3:       '0 8px 24px rgba(13,30,55,.10), 0 2px 8px rgba(13,30,55,.06)',
        sh4:       '0 18px 48px rgba(13,30,55,.18), 0 4px 12px rgba(13,30,55,.08)',
        'sh-brand':'0 8px 22px rgba(12,60,96,.28)',
      },
      height: {
        topbar:      '56px',
        btn:         '48px',
        'btn-sm':    '36px',
        'btn-xs':    '30px',
        'icon-btn':  '40px',
        fab:         '56px',
        'avatar-xs': '22px',
        'avatar-sm': '28px',
        avatar:      '32px',
        'avatar-lg': '48px',
        'avatar-xl': '64px',
      },
      width: {
        'icon-btn':  '40px',
        fab:         '56px',
        'avatar-xs': '22px',
        'avatar-sm': '28px',
        avatar:      '32px',
        'avatar-lg': '48px',
        'avatar-xl': '64px',
        'app-frame': '480px',
      },
      maxWidth: {
        'app-frame': '480px',
      },
      minHeight: {
        dvh: '100dvh',
      },
      spacing: {
        // Design token aliases (px-value naming)
        '4px':  '4px',
        '8px':  '8px',
        '12px': '12px',
        '14px': '14px',
        '16px': '16px',
        '20px': '20px',
        '24px': '24px',
        '32px': '32px',
        '40px': '40px',
        '48px': '48px',
        '56px': '56px',
        '72px': '72px',
      },
      zIndex: {
        fab:       '25',
        topbar:    '30',
        sheet:     '50',
        search:    '55',
        modal:     '60',
        toast:     '80',
      },
    },
  },
  safelist: [
    { pattern: /^bg-(c[1-9]|c10)(-soft)?$/ },
    { pattern: /^text-(c[1-9]|c10)$/ },
    { pattern: /^border-(c[1-9]|c10)$/ },
  ],
  plugins: [],
}

export default config
